/* Run after browser-setup.php; requires Playwright's installed Chrome browser. */
const { chromium } = require( 'playwright' );
const fs = require( 'fs' );
const path = require( 'path' );
const assert = require( 'assert/strict' );
const fixturePath = require( './fixture-path.cjs' );
const fixture = JSON.parse( fs.readFileSync( fixturePath( 'browser-fixture' ) ) );
const output = path.join( __dirname, '../test-results' );
const checks = [];
const check = ( ok, message ) => { assert( ok, message ); checks.push( message ); console.log( 'PASS ' + message ); };
(async () => {
 const browser = await chromium.launch( { channel: 'chrome', headless: true } );
 try {
  const context = await browser.newContext();
  const page = await context.newPage();
  const errors = [];
  page.on( 'pageerror', e => errors.push( e.message ) );
  for ( const width of [375, 768, 1024, 1440] ) {
   await page.setViewportSize( { width, height: 1000 } );
   await page.goto( fixture.url, { waitUntil: 'networkidle' } );
   await page.locator( '.rise-lp__hero' ).waitFor();
   check( await page.locator( '.rise-lp__section' ).count() === 6, `${width}px: six sections rendered` );
   const layout = await page.evaluate( () => ( { scroll: document.documentElement.scrollWidth, viewport: innerWidth, hero: getComputedStyle(document.querySelector('.rise-lp__hero')).display, cards: Array.from(document.querySelectorAll('.rise-lp__service-card')).map(el => Math.round(el.getBoundingClientRect().top)) } ) );
   check( layout.scroll <= layout.viewport, `${width}px: no horizontal overflow` );
   if ( width === 375 ) check( new Set(layout.cards).size === 3, 'Mobile service cards stack vertically' );
   if ( width >= 1024 ) check( new Set(layout.cards).size === 1, `${width}px: service cards form a row` );
   await page.screenshot( { path: path.join( output, `landing-${width}.png` ), fullPage: true } );
  }
  check( await page.locator( '#main-header, #main-footer, #page-container, .et-l--header, .et-l--footer' ).count() === 0, 'No Divi header, footer, or page wrapper' );
  check( await page.locator( 'h1' ).count() === 1, 'Exactly one page heading' );
  check( await page.locator( 'head title' ).count() === 1 && (await page.title()).includes('Rise QA'), 'WordPress document title retained' );
  check( !fixture.url.includes('/landing-page/') && fixture.url.includes('/rise-qa-campaign-'), 'Published page has a clean native page URL' );
  const faq = page.locator( '.rise-lp__faq-question' ).first();
  await faq.focus();
  check( await faq.getAttribute( 'aria-expanded' ) === 'false', 'FAQ initially collapsed after enhancement' );
  await page.keyboard.press( 'Enter' );
  check( await faq.getAttribute( 'aria-expanded' ) === 'true', 'Enter expands FAQ' );
  const answerId = await faq.getAttribute('aria-controls');
  await page.locator('#'+answerId).waitFor({state:'visible'});
  check( await page.locator('#'+answerId).isVisible(), 'aria-controls references the visible answer' );
  await page.keyboard.press( 'Space' );
  check( await faq.getAttribute( 'aria-expanded' ) === 'false' && await page.locator('#'+answerId).getAttribute('inert') !== null, 'Space immediately updates FAQ state and removes closing content from the tab order' );
  await page.locator('#'+answerId).waitFor({state:'hidden'});
  check( !await page.locator('#'+answerId).isVisible(), 'FAQ answer is hidden when the closing animation completes' );
  await page.keyboard.press( 'ArrowDown' );
  check( await page.locator( '.rise-lp__faq-question' ).nth(1).evaluate(el => el === document.activeElement), 'Arrow keys move between FAQ questions' );
  await page.addScriptTag({path: require.resolve('axe-core/axe.min.js')});
  const audit = await page.evaluate(async()=>await axe.run('.rise-lp',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}));
  fs.writeFileSync(path.join(output,'accessibility.json'),JSON.stringify(audit.violations,null,2));
  check(audit.violations.length === 0, 'Default landing layout has no axe WCAG A/AA violations');
  check( errors.length === 0, 'Frontend has no uncaught JavaScript errors' );
  const noJS = await browser.newContext( { javaScriptEnabled: false } );
  const noJSPage = await noJS.newPage();
  await noJSPage.goto( fixture.url );
  check( await noJSPage.locator('.rise-lp__faq-answer').first().isVisible(), 'FAQ remains readable without JavaScript' );
  await noJS.close();
  await page.goto( fixture.normalURL, {waitUntil:'networkidle'} );
  check( await page.locator('link[href*="assets/frontend.css"],script[src*="assets/frontend.js"]').count() === 0, 'Normal frontend page has no Rise frontend assets' );
  await context.addCookies( fixture.cookies );
  await page.goto( fixture.baseURL + '/wp-admin/edit.php?post_type=page&rise_landing=1', { waitUntil:'networkidle' } );
  console.log('Admin location:',page.url(),await page.locator('h1').allTextContents());
  check( await page.locator('.wrap h1').first().innerText() === 'Rise Landing Pages', 'Dedicated list opens with the Rise title' );
  check( await page.getByRole('link',{name:'Rise QA campaign',exact:true}).count() === 1 && await page.getByRole('link',{name:'Rise QA normal page',exact:true}).count() === 0, 'Landing list contains Rise pages only' );
  const add = page.locator('.page-title-action');
  await add.click();
  await page.waitForURL(/post\.php\?post=\d+&action=edit/);
  const newID = Number(new URL(page.url()).searchParams.get('post'));
  const extraPath=fixturePath('browser-extra-ids');
  const extras = [...(fs.existsSync(extraPath)?JSON.parse(fs.readFileSync(extraPath)):[]),newID];
  fs.writeFileSync(extraPath,JSON.stringify(extras),{mode:0o600});
  await page.waitForFunction(()=>window.wp?.data?.select('core/block-editor')?.getBlocks().length===6, {timeout:30000});
  const editor = await page.evaluate(()=>({names:wp.data.select('core/block-editor').getBlocks().map(b=>b.name), allowed:wp.data.select('core/block-editor').getSettings().allowedBlockTypes, meta:wp.data.select('core/editor').getEditedPostAttribute('meta'),removable:wp.data.select('core/block-editor').getBlocks().every(b=>wp.data.select('core/block-editor').canRemoveBlock(b.clientId))}));
  check(editor.names.length === 6 && editor.names.every(n=>n.startsWith('rise-landing/')), 'Add Landing Page opens Gutenberg with six custom blocks');
  check(Array.isArray(editor.allowed)&&editor.allowed.length===9&&editor.allowed.every(n=>n.startsWith('rise-landing/')), 'Live Gutenberg allow-list contains Rise blocks and the Hero child block');
  check(editor.meta._rise_landing_page === true && editor.removable, 'Live editor has page marker and allows section removal');
  const heroFeatures=await page.evaluate(()=>({size:!!wp.data.select('core/rich-text')?.getFormatType?.('rise-landing/size'),second:wp.blocks.getBlockType('rise-landing/hero').attributes.secondaryStyle?.default}));
  check(heroFeatures.size&&heroFeatures.second==='outline','Hero inline size and second button controls are registered');
  await page.evaluate(()=>{const store=wp.data.select('core/block-editor');const block=store.getBlocks()[5];window.riseQARemovedBlock=block;wp.data.dispatch('core/block-editor').removeBlock(block.clientId);});
  await page.waitForFunction(()=>wp.data.select('core/block-editor').getBlocks().length===5);
  check(await page.evaluate(()=>wp.data.select('core/block-editor').getBlocks().length)===5,'Client can remove a complete landing section');
  await page.evaluate(()=>wp.data.dispatch('core/block-editor').insertBlock(window.riseQARemovedBlock,5));
  await page.waitForFunction(()=>wp.data.select('core/block-editor').getBlocks().length===6);
  const invalid = await page.evaluate(()=>wp.data.select('core/block-editor').getBlocks().filter(b=>!b.isValid).length);
  check(invalid === 0, 'All editor blocks validate');
  await page.screenshot({path:path.join(output,'editor.png'),fullPage:true});
  await page.goto(fixture.baseURL + '/wp-admin/admin.php?page=rise-landing-settings',{waitUntil:'networkidle'});
  check(await page.locator('#rise-setting-brand_name').count()===1,'Brand settings screen loads');
  await page.screenshot({path:path.join(output,'settings.png'),fullPage:true});
  await page.goto(fixture.baseURL + '/wp-admin/edit.php?post_type=page&rise_landing=1',{waitUntil:'networkidle'});
  const row = page.locator('#post-'+fixture.ids[0]);
  await row.hover();
  await row.getByRole('link',{name:'Duplicate landing page'}).click();
  await page.waitForURL(/post\.php\?post=\d+&action=edit/);
  const dupID = Number(new URL(page.url()).searchParams.get('post'));
  extras.push(dupID);
  fs.writeFileSync(extraPath,JSON.stringify(extras),{mode:0o600});
  await page.waitForFunction(()=>window.wp?.data?.select('core/editor')?.getCurrentPost()?.status==='draft');
  check(await page.evaluate(()=>wp.data.select('core/editor').getCurrentPost().title)==='Copy of Rise QA campaign','Duplicate action opens a correctly named draft');
  await page.goto(fixture.baseURL+'/wp-admin/post.php?post='+fixture.ids[1]+'&action=edit',{waitUntil:'domcontentloaded'});
  await page.waitForFunction(()=>window.wp?.data?.select('core/block-editor')?.getSettings());
  const ordinary = await page.evaluate(()=>({script:!!document.querySelector('script#rise-landing-editor-js')}));
  check(!ordinary.script,'Ordinary page editor does not load the Rise editor bundle');
  fs.writeFileSync(path.join(output,'browser-report.json'),JSON.stringify({checks,errors},null,2));
  console.log(`${checks.length} browser assertions passed.`);
 } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exitCode=1;});
